"""UUID type in id column

Revision ID: 5448b76825c6
Revises: 870093669fd7
Create Date: 2023-04-02 14:36:08.686101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5448b76825c6'
down_revision = '870093669fd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_headquarters_id', table_name='headquarters')
    op.drop_index('ix_organizations_id', table_name='organizations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    op.create_index('ix_headquarters_id', 'headquarters', ['id'], unique=False)
    # ### end Alembic commands ###
