"""V3_0 identification Enum

Revision ID: b0eef663a7b1
Revises: 5448b76825c6
Create Date: 2023-04-02 18:15:43.630946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0eef663a7b1'
down_revision = '5448b76825c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
